### ISSUE TITLE
Hi，there is some thing wrong with the waifu2x model,need help,QAQ

### ISSUE THREAD

**Issue by xjrelc** [rapidrabbit76/PaintsTensorFlow#2]
emmm,the waifu2x.zip which is contains another saved model paintstensorflowmodel.zip....
when i run it came out the error like that:
Traceback (most recent call last):
  File "runGUI.py", line 7, in <module>
    w = Window()
  File "C:\Users\acer-pc\Desktop\tool\PaintsTensorFlow\GUI\paintingView.py", line 21, in __init__
    self.tensor_module = TensorModule()
  File "C:\Users\acer-pc\Desktop\tool\PaintsTensorFlow\GUI\tensorModul\TensorModule.py", line 20, in __init__
    self.__waifu2x = Waifu2x(sess=self.sess)
  File "C:\Users\acer-pc\Desktop\tool\PaintsTensorFlow\GUI\tensorModul\Waifu2x.py", line 19, in __init__
    self.__zero_init()
  File "C:\Users\acer-pc\Desktop\tool\PaintsTensorFlow\GUI\tensorModul\Waifu2x.py", line 26, in __zero_init
    self.__model.predict(feed)
  File "D:\Anaconda3\envs\paint\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1864, in predict
    x, check_steps=True, steps_name='steps', steps=steps)
  File "D:\Anaconda3\envs\paint\lib\site-packages\tensorflow\python\keras\engine\training.py", line 992, in _standardize_user_data
    class_weight, batch_size)
  File "D:\Anaconda3\envs\paint\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1117, in _standardize_weights
    exception_prefix='input')
  File "D:\Anaconda3\envs\paint\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 293, in standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],...

**Comment by rapidrabbit76** [comment]
oh... sorry...  just checked the link and confirmed that I uploaded the "waifu2x" model incorrectly.

Download the "waifu2x" saved_model from the new link  [here](https://drive.google.com/open?id=1R86g3_G5INvVV4Vx4xiflezK_U5L5CwD)
you seem to be using "Windows", but my working environment was "Ubuntu 18.04".
so...  I do not think I can guarantee that it will work correctly.

If you have any other questions, please post them anytime.
I hope my answer is helpful!
# The readme has just been modified with a new file link.

**Comment by xjrelc** [comment]
Thanks a lot !!! Your project is also can work correctly in windows~

**Comment by Xsz777** [comment]
> Thanks a lot !!! Your project is also can work correctly in windows~
Hi~Can you share the models. Thank you!

**Comment by rapidrabbit76** [comment]
@Xsz777 
#9 Please note. Sorry, We will make it available for download within next week.
